### ISSUE TITLE
もふもふさんのキャラクター設定

### ISSUE THREAD

**Issue by KasuyaMofu** [KasuyaMofu/backyard#1]

**Comment by Moffu360** [comment]
もふもふさんは、拾われた猫。こういう見た目をしていた。

```
　　∧　 ∧
　ミ・ω・彡
〜ミ　　  彡
```

**Comment by Moffu360** [comment]
元の姿の大きさ：TBD

人間の姿の大きさ：
B: TBD
W: TBD
H: TBD

**Comment by Moffu360** [comment]
人間での名前は「糟屋 もふ」

**Comment by Moffu360** [comment]
## キャラクターのストーリー

### 家主

福岡県糟屋郡に住んでいるエンジニア。仕事でいつも帰りが遅く、疲れてそう。

### 家主との出会い

福岡県糟屋郡新宮町の相島、通称"猫島"の猫。

link: https://goo.gl/maps/fom4KyiXxb9CPWNo6

家主が釣りをしているところを見続けていて、
家主のバッグにひっそりと紛れているうちに寝てしまっていた。
家主もそんなことは知らず、ボーっと帰ってきて新宮漁港に着いてから気づいた。

どうしたもんかと座っている家主としばらく目を丸くして見つめ合った後、横について首を服にスリスリして、「うちに来るかい？」と言っていたので、うんうんと首を縦に振って連れて行ってもらった。

### 普段の生活

家主が家を空けがちなので、適当にお出かけをする。

### 人の姿になったきっかけ

南蔵院の大仏の前で( ˘ω˘)ｽﾔｧしてたら、いつのまにか同じ姿で( ˘ω˘)ｽﾔｧしてた。

**Comment by Moffu360** [comment]
## 衣装

服はもっぱらユニクロ。夏はエアリズムを、冬はヒートテックを欠かせない。

**Comment by Moffu360** [comment]
①髪型について

* 手触り、弾力
  * つむじから生えててさらさらな1本ずつの髪の毛が集まっている
  * 順方向（つむじから毛先）はさらさらしていて、そこから横向きに触るとざらざら、指でつぶす感じに触るともちもちしている
* 重さ
  * スプラトゥーンの髪型みたいにある程度ビタンビタンしてる
* 模様の部分に凹凸はない

②お面について
2つ用意している

* ヘアピン（ある程度大きい、プラスチックみたいに固めでちょっと重い、お出かけ用）
* 紐（裏側にちょうちょ結び、軽い素材、小さい、ラフなとき用）

**Comment by KasuyaMofu** [comment]
とりあえず今はいいや
