### ISSUE TITLE
使うツールを整理する

### ISSUE THREAD

**Issue by KasuyaMofu** [KasuyaMofu/backyard#6]

**Comment by Moffu360** [comment]
## GitHub

何する: 進捗を整理する、ToDoを管理する、情報をメモする。
何をしない: 整理、構造化したデータは書かない。

https://github.com/Moffu360/

**Comment by Moffu360** [comment]
## Notion

https://www.notion.so/moffulab/

### 何をする 

整理、構造家したデータを書く。

### 何をしない

サイトのホスティングはしない。

**Comment by Moffu360** [comment]
## Adobe Creative Cloud

https://www.adobe.com/jp/creativecloud.html

### 何をする

イラスト・動画作成にかかわる全て。

### 何をしない

それ以外。DreamweaverなどのWebサイトの作成といった使えそうなものは、評価後。

**Comment by KasuyaMofu** [comment]
このissueはいいかな。どっかでサブスクリプションまとめをする気がするので、その時にでも見直そう
