### ISSUE TITLE
ラジオコンテンツ(infradio)の設計

### ISSUE THREAD

**Issue by KasuyaMofu** [KasuyaMofu/backyard#8]

**Comment by Moffu360** [comment]
ロゴとかのデザイン

```
infrad.io
__________
by infra engineer,
be informal,
     infinity topics.
```

**Comment by Moffu360** [comment]
ハッシュタグは #infradio 。現時点で存在していないことを確認
![Screenshot_20200804-040320.png](https://user-images.githubusercontent.com/56345674/89217678-8b652c00-d607-11ea-9333-f963cbe78df4.png)

**Comment by Moffu360** [comment]
ドメインは取りたいな。書くと先行取得されるので、取得したら書く

**Comment by Moffu360** [comment]
コンテンツ公開はYattecastで良さそう。技術書展ですでに書籍も持ってるので、やりやすいと思う

https://r7kamura.github.io/yattecast/

**Comment by Moffu360** [comment]
とはいえ、最近はYouTubeでコンテンツを流すのが主流なので、音源と概要はYouTubeとduplicateする形。

**Comment by Moffu360** [comment]
`infrad.io` はすでに取得済みだったので、 infradio.net を取得した。
![image](https://user-images.githubusercontent.com/56345674/89254424-0eaf6d80-d65a-11ea-87ce-1fa004447447.png)

**Comment by Moffu360** [comment]
登録終わった。早い
![image](https://user-images.githubusercontent.com/56345674/89255328-6949c900-d65c-11ea-9606-60fce02358b6.png)

**Comment by Moffu360** [comment]
おつとめ終わった後に読む
https://www.amazon.co.jp/dp/B07FJ61FD3

**Comment by Moffu360** [comment]
リリースノートリーディング
リリリ

**Comment by Moffu360** [comment]
jvn読みもいいね

**Comment by Moffu360** [comment]
ライト版、ディープ版にわける

**Comment by Moffu360** [comment]
曜日によっては、特に火曜日はディープ版にしたい。
そういう新情報のプレス月曜日に出て、Twitterでそれなりに話題になったあと届くので、頭にも入りやすい。

**Comment by Moffu360** [comment]
インフラエンジニアの地位向上とか、その辺のテンプレで返せる考え方は伝え方をまとめておいたほうが良い。
