### ISSUE TITLE
声を改善する

### ISSUE THREAD

**Issue by KasuyaMofu** [KasuyaMofu/backyard#9]

**Comment by Moffu360** [comment]
https://www.youtube.com/watch?v=5XdaKrhgSmc&feature=youtu.be

・「えーっと」とか「ん－」とかも抑える
・音程が裏返る瞬間がかなり聞いてて気持ちよくない（た↓と↑えば～とか）。配信の中でも印象が最悪な部類。
・もっとマイクから離れる。ブレスが入りすぎなのと、距離感が近すぎる。
